spring.application.name=Java_5seminars


#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=userspring
#spring.datasource.password=${DB_PASSWORD}
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true

#lokalajam mysql serverim
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/minirimi
spring.datasource.username=userspring
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

#vea mysql serverim ar vpn
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.datasource.url=jdbc:mysql://10.0.6.178:3306/RitvarsBadersdb
#spring.datasource.username=RitvarsBaders
#spring.datasource.password=${DB_PASSWORD} skepasta
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver


#show databses;
#use minirimi;
#show tables;
#describe product_table;
#select * from product_table;
